name: Build & Test
on:
  workflow_call:
    inputs:
      platform_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      std_version:
        required: true
        type: string
      version:
        required: true
        type: string
env:
  BUILD_TYPE: Debug
  CC: /usr/bin/gcc-${{inputs.version}}
  CXX: /usr/bin/g++-${{inputs.version}}
jobs:
  build:
    runs-on: ${{inputs.image_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Initialize submodules
        run: git submodule update --init
      - name: Install GCC ${{inputs.version}}
        run: sudo apt install -y gcc-${{inputs.version}} g++-${{inputs.version}}
      - name: Configure CMake (${{inputs.platform_name}})
        run: cmake -B ${{github.workspace}}/build-${{inputs.platform_name}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{inputs.std_version}}
      - name: Build (${{inputs.platform_name}})
        run: cmake --build ${{github.workspace}}/build-${{inputs.platform_name}} --config ${{env.BUILD_TYPE}} --clean-first
      - name: Test (${{inputs.platform_name}})
        working-directory: ${{github.workspace}}/build-${{inputs.platform_name}}
        run: ctest -C ${{env.BUILD_TYPE}}